package com.algorithm.data.order.dao;

import com.algorithm.data.order.bean.OrderItem;
import com.algorithm.data.order.bean.OrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     */
    long countByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     */
    int deleteByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long orderItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OrderItem selectOneByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OrderItem selectOneByExampleSelective(@Param("example") OrderItemExample example, @Param("selective") OrderItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<OrderItem> selectByExampleSelective(@Param("example") OrderItemExample example, @Param("selective") OrderItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     */
    List<OrderItem> selectByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OrderItem selectByPrimaryKeySelective(@Param("orderItemId") Long orderItemId, @Param("selective") OrderItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     */
    OrderItem selectByPrimaryKey(Long orderItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<OrderItem> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_0
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<OrderItem> list, @Param("selective") OrderItem.Column ... selective);
}